### ISSUE TITLE
config.load() can lead to infinite loop in recursive mode

### ISSUE THREAD

**Issue by ltriess** [zhijian-liu/torchpack#10]
I observed that the `load()` function from `torchpack/utils/config.py` can be stuck in an infinite loop when recursive mode is enabled. In particular this happens when the path to the config is given as an absolute path instead of a relative path. When the top-level directory `"/"` is reached, `os.path.dirname("/")` will again return "/" and the `while` loop never ends.
See example for the development of the variable `fpath` in `load()` below:
```
/code/configs/config.yaml
/code/configs
/code
/
/
... (infinite)
/
```
The program will finally crashed with a memory error caused by a memory leak of the list `fpaths` to which infinite paths are appended.

**Comment by zhijian-liu** [comment]
Thanks for bringing this up. I will work on a fix and let you know once it's merged. At the same time, you can try to use the relative path for now to avoid this issue.

**Comment by zhijian-liu** [comment]
Hi @ltriess, I just pushed a fix to the master branch. Could you please have a try and let me know if the issue has been resolved.

**Comment by ltriess** [comment]
Yes, thank you.
