### ISSUE TITLE
YAML Formatting

### ISSUE THREAD

**Issue by raunakdoesdev** [zhijian-liu/torchpack#12]
YAML lists should be formatted compactly as `[1, 2, 3, 4]` rather than
```
- 1
- 2
- 3
- 4
```

**Comment by sauhaardac** [comment]
I think this issue can be managed by the [default_flow_style kwarg](https://pyyaml.org/wiki/PyYAMLDocumentation#Dictionarieswithoutnestedcollectionsarenotdumpedcorrectly). Should I change the default kwarg to be "default_flow_style=True"? @zhijian-liu

**Comment by zhijian-liu** [comment]
Thanks! I actually tried to tweak this before; however, it does not work as expected.

Here is a sample testing code:
```
import yaml
import tempfile

configs = {
    'a': 1,
    'b': [1, 2, 3, 4],
    'c': {
        'd': 1
    }
}

for default_flow_style in [True, False, None]:
    print(yaml.dump(configs, default_flow_style=default_flow_style))
```

The output of `default_flow_style=True` is
```
{a: 1, b: [1, 2, 3, 4], c: {d: 1}}
```
The output of `default_flow_style=False` is
```
a: 1
b:
- 1
- 2
- 3
- 4
c:
  d: 1
```
The output of `default_flow_style=None` is
```
a: 1
b: [1, 2, 3, 4]
c: {d: 1}
```

I somehow expect a mixture of the last two:
```
a: 1
b: [1, 2, 3, 4]
c:
  d: 1
```
Would love to know what you think. Thanks!

**Comment by sauhaardac** [comment]
Thanks for the explainer! I found the solution here:
https://stackoverflow.com/a/56939573/4674299
https://github.com/yaml/pyyaml/pull/256

I'll set the default_flow_style to None and send a PR soon.
