### ISSUE TITLE
AMP Support

### ISSUE THREAD

**Issue by CCInc** [zhijian-liu/torchpack#16]
Hi, I wonder if we could add in AMP support now that torchsparse supports mixed precision. I think it would just require addition of `GradScaler` and an `amp.autocast` block.

**Comment by zhijian-liu** [comment]
This is not supposed to be natively supported in TorchPack as the philosophy of TorchPack is to not interfere with the actual forward/backward pass. Using AMP should only add a few lines to `Trainer`, which you can refer to https://github.com/zhijian-liu/torchpack/blob/master/examples/image-classification/core/trainers.py#L34-L44.

**Comment by CCInc** [comment]
I'm sorry, I did not read the _run_step close enough. Thanks!
