### ISSUE TITLE
Distributed train problem

### ISSUE THREAD

**Issue by moshicaixi** [zhijian-liu/torchpack#24]
when I run the commad 'torchpack dist-run -np 3 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml' , I got a error as follows. Could you please tell me how can I resolve this problem? Thanks very much!

ssh: Could not resolve hostname localhost:3: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

**Comment by zhijian-liu** [comment]
Could you share the output of `mpirun --version`? Thanks!

**Comment by moshicaixi** [comment]
I forgot to update my issue. At first, I used mpich for my mpi environment, which caused this error. When I changed to openmpi, It became normal. Thanks for your reply!

**Comment by zhijian-liu** [comment]
Sounds good. Thanks for your update.
