### ISSUE TITLE
save and load

### ISSUE THREAD

**Issue by chky1997** [zhijian-liu/torchpack#29]
Hi, I'm trying to use torchpack to simplify my model, but I got confused while using the save and load part. 
Now I can save the .pt file under the checkpoints dir using 'Saver()', but I don't know how to load the .pt file. Could you please give me some advice? Thank you!

**Comment by zhijian-liu** [comment]
You can simply load the saved checkpoint with `torch.load()` or `io.load` (from `torchpack.utils`).
