### ISSUE TITLE
Installing Torchpack removing older version of Torch

### ISSUE THREAD

**Issue by sri13** [zhijian-liu/torchpack#33]
Collecting torch>=1.5.0
  Using cached torch-1.11.0-cp38-cp38-manylinux1_x86_64.whl (750.6 MB)
  ****
   Attempting uninstall: torch
    Found existing installation: torch 1.10.2
    Uninstalling torch-1.10.2:
      Successfully uninstalled torch-1.10.2
Successfully installed ** torch-1.11.0 **

**Comment by zhijian-liu** [comment]
This seems to be related to https://github.com/pypa/pip/issues/304. Could you try if this works?
```
pip install --upgrade --upgrade-strategy=only-if-needed torchpack
```

**Comment by sri13** [comment]
Thanks. It fixed the issue.
