### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by chendaozai** [zhijian-liu/torchpack#36]
Hi! When I run `torchpack dist-run -np 2 python train.py configs/s3dis/from_scratch.yaml --run-dir ./s3dis_out`,there is a error:
<[mpiexec@cappuccino-Super-Server] match_arg (utils/args/args.c:163): unrecognized argument allow-run-as-root
[mpiexec@cappuccino-Super-Server] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@cappuccino-Super-Server] parse_args (ui/mpich/utils.c:1642): error parsing input array
[mpiexec@cappuccino-Super-Server] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1694): unable to parse user arguments
[mpiexec@cappuccino-Super-Server] main (ui/mpich/mpiexec.c:148): error parsing parameters>

**Comment by zhijian-liu** [comment]
I think you have installed MPICH instead of OpenMPI. You could do `which mpirun` to find where your current MPI is installed.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to its inactivity. However, please feel free to reopen it if your problem persists.
