### ISSUE TITLE
Package not intialized

### ISSUE THREAD

**Issue by dvando** [zhijian-liu/torchpack#37]
HI Zhijian, found out you might forget to import all the packages in __init__.py. 
![image](https://user-images.githubusercontent.com/63303799/187860757-e46bed84-57f6-4392-8a6a-65f60206b727.png)

I imported them manually in the __init__.py file.
![image](https://user-images.githubusercontent.com/63303799/187861432-687f6b94-3f64-4a8e-8837-59b4d73577d0.png)

Or is there any reason why did you leave the packages unimported?
Anyway, thanks for the good work!

**Comment by zhijian-liu** [comment]
Thanks, @dvando! These packages are not required to be imported in my use cases (by `from torchpack.abc import xyz`). Could you please provide an example that requires these packages being imported? Thank you!

**Comment by dvando** [comment]
It was when I tried to use the [bevfusion](https://github.com/mit-han-lab/bevfusion), I encountered the error "module 'torchpack' has no attribute 'utils'", I checked the module and found out that I just needed to reinitialize it. 
p.s: It's the first time I'm using torchpack.

**Comment by zhijian-liu** [comment]
Thanks! Would you mind submitting a PR for this issue?

**Comment by dvando** [comment]
Sure, I'll close this issue too, thanks @zhijian-liu !
