### ISSUE TITLE
Segmentation fault (core dumped) when ` from torchpack.callbacks import Callbacks, SaverRestore`

### ISSUE THREAD

**Issue by hwLiu8** [zhijian-liu/torchpack#40]
when my program has this code : `from torchpack.callbacks import Callbacks, SaverRestore`, it occur `Segmentation fault (core dumped)`, who knew why??  thanks.

**Comment by zhijian-liu** [comment]
This is very wield. Could you make sure that you could reproduce this error just with this line alone?
