### ISSUE TITLE
Import torchpack.callbacks will raise Failed to import tensorflow warning

### ISSUE THREAD

**Issue by fangliancheng** [zhijian-liu/torchpack#41]
Hi Zhijian，

I found when I import torchpack.callbacks with the following code:
```
from torchpack.callbacks import Callback

def main():
    print('main called')
    
if __name__=='__main__':
    main()
```

A warning will be raise:
```
Failed to import tensorflow.
main called
```

I checked the callback classes, but didn't find where tensorflow is imported, so I am confused why such warning is raised. Any help would be appreciated! 

Best regards,
Liancheng Fang

**Comment by zhijian-liu** [comment]
It's due to `tensorpack`, which we remove its dependency in the latest version. Could you try to install the latest version from GitHub?
