### ISSUE TITLE
torchpack without command line

### ISSUE THREAD

**Issue by sandeepnmenon** [zhijian-liu/torchpack#42]
I have been using torchpack for my experiments. Now I need to integrate my model training code into another codebase built on Bazel.
I am not able to use the torchpack command line tool and run like
```
torchpack dist-run -np 1 python train.py
```
I have installed torchpack using pip. Is there a way to replicate the same behavior through python executable
(similar to `python3 -m torch.distributed.launch train.py`)

**Comment by zhijian-liu** [comment]
I think you should be able to do `python train.py`. Make sure you have upgraded to the latest version on GitHub.

**Comment by sandeepnmenon** [comment]
I am using the latest version mentioned in the releases (`v0.3.1`). But then I run with just `python train.py` and the train.py fails at `dist.init()`
```python
from torchpack import distributed as dist
from torchpack.environ import auto_set_run_dir, set_run_dir
from torchpack.utils.config import configs
dist.init()
torch.backends.cudnn.benchmark = cfg.cudnn_benchmark
torch.cuda.set_device(dist.local_rank())
```
with the error
```bash
  File "/home/s.menon/vehicle/./bazel-bin/source/offboard/ml/third_party/bevfusion/train.runfiles/vehicle/source/offboard/ml/third_party/bevfusion/train.py", line 55, in main
    dist.init()
  File "/home/s.menon/vehicle/bazel-bin/source/offboard/ml/third_party/bevfusion/train.runfiles/offboard_python_analysis_torchpack/site-packages/torchpack/distributed/context.py", line 23, in init
    master_host = 'tcp://' + os.environ['MASTER_HOST']
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'MASTER_HOST'
```

Is there another way to use torchpack without the command line executable?

**Comment by zhijian-liu** [comment]
You probably need to install the latest version from the master branch.

**Comment by sandeepnmenon** [comment]
Yes, that worked. Thank you very much!
It was confusing because even with installing from the master, the version was coming as `0.3.1`

**Comment by sandeepnmenon** [comment]
How can I replicate the distributed environment inside the `train.py`? using the torchpack api
```
torchpack dist-run -np 4
```

**Comment by sandeepnmenon** [comment]
@zhijian-liu When I just run `python train.py` with
```
from torchpack import distributed as dist
from torchpack.environ import auto_set_run_dir, set_run_dir
from torchpack.utils.config import configs
dist.init()
torch.backends.cudnn.benchmark = cfg.cudnn_benchmark
torch.cuda.set_device(dist.local_rank())
```
I get the message
`[2023-07-18 20:26:04.243] Distributed environment not detected, fall back to default`
How to set the master port and set up the distributed training with `N` GPUs replicating 
`torchpack dist-run -np N` in side the `train.py` and enforce it with a normal python call

**Comment by zhijian-liu** [comment]
I think it's hard to set the distributed environment within the script directly.
