### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by wulinaaa** [zhijian-liu/torchpack#44]
When I use the torchpack command and run like:
torchpack dist-run -np 1 python train.py
I have been running for several days, but there is no output. Can you please help me understand why?
I set batch_size=1, it still no output.

**Comment by zhijian-liu** [comment]
Could you double-check if you can get any results by `torchpack dist-run -np 1 hostname`?

**Comment by wulinaaa** [comment]
Yes, my hostname will be output.

**Comment by wulinaaa** [comment]
I found the reason, which is that I wanted to download the CUDA version of Torch.

**Comment by Sadwy** [comment]
> Could you double-check if you can get any results by `torchpack dist-run -np 1 hostname`?

I tried but there was no output. It was just left as it is in the picture for more than twenty minutes. Any suggestions?
![image](https://github.com/zhijian-liu/torchpack/assets/45492880/78eeb9a2-d9a0-4e0d-b824-1638bbabbddc)

**Comment by Sadwy** [comment]
> > > 你能仔细检查一下你是否可以得到任何结果吗？`torchpack dist-run -np 1 hostname`
> > 
> > 
> > 我试过了，但没有输出。它只是在图片中保持原样二十多分钟。有什么建议吗？ ![image](https://user-images.githubusercontent.com/45492880/263247554-78eeb9a2-d9a0-4e0d-b824-1638bbabbddc.png)
> 
> 你这个输出有问题啊，正确的输出应该是你的主机名，你看看你的torchpack安装好了没

上一张图里是因为加了`-v`参数后会打印verbose信息, 如果不加`-v`参数就没有任何输出了, 见下图:
- p2 ![image](https://github.com/zhijian-liu/torchpack/assets/45492880/19a13a0e-8c28-4ae5-83f3-4cd40f5aee1a)

torchpack应该是安装好了, 执行`torchpack -h`会有输出, 如下图:
- p3 ![image](https://github.com/zhijian-liu/torchpack/assets/45492880/0f0d947c-c162-47ae-8f80-8ea326505954)

现在我遇到的问题是执行`CUDA_VISIBLE_DEVICES="0,1" torchpack dist-run -np 2 python tools/test.py`时也没有任何响应, 执行几十分钟了也不输出任何信息.

**Comment by wulinaaa** [comment]
> > > > 你能仔细检查一下你是否可以得到任何结果吗？`torchpack dist-run -np 1 hostname`
> > > 
> > > 
> > > 我试过了，但没有输出。它只是在图片中保持原样二十多分钟。有什么建议吗？ ![image](https://user-images.githubusercontent.com/45492880/263247554-78eeb9a2-d9a0-4e0d-b824-1638bbabbddc.png)
> > 
> > 
> > 你这个输出有问题啊，正确的输出应该是你的主机名，你看看你的torchpack安装好了没
> 
> 上一张图里是因为加了`-v`参数后会打印verbose信息, 如果不加`-v`参数就没有任何输出了, 见下图:
> 
> * p2 ![image](https://user-images.githubusercontent.com/45492880/263253585-19a13a0e-8c28-4ae5-83f3-4cd40f5aee1a.png)
> 
> torchpack应该是安装好了, 执行`torchpack -h`会有输出, 如下图:
> 
> * p3 ![image](https://user-images.githubusercontent.com/45492880/263253860-0f0d947c-c162-47ae-8f80-8ea326505954.png)
> 
> 现在我遇到的问题是执行`CUDA_VISIBLE_DEVICES="0,1" torchpack dist-run -np 2 python tools/test.py`时也没有任何响应, 执行几十分钟了也不输出任何信息.

你pip list看一下torchpack是不是0.3.1，如果没问题，可能是环境的问题，我之前跟你一样，没有任何响应，GPU也不占用

**Comment by Sadwy** [comment]
torchpack的版本是0.3.1
- p4 ![image](https://github.com/zhijian-liu/torchpack/assets/45492880/786a7e9b-6ec3-4468-91ac-c4749db07c20)
请问你最后怎么解决的呢? 没有响应也不占GPU, 我不知道该如何下手去找bug.

**Comment by wulinaaa** [comment]
> torchpack的版本是0.3.1
> 
> * p4 ![image](https://user-images.githubusercontent.com/45492880/263257341-786a7e9b-6ec3-4468-91ac-c4749db07c20.png)
>   请问你最后怎么解决的呢? 没有响应也不占GPU, 我不知道该如何下手去找bug.

我重新搭建了环境

**Comment by Sadwy** [comment]
> > torchpack的版本是0.3.1
> > 
> > * p4 ![image](https://user-images.githubusercontent.com/45492880/263257341-786a7e9b-6ec3-4468-91ac-c4749db07c20.png)
> >   请问你最后怎么解决的呢? 没有响应也不占GPU, 我不知道该如何下手去找bug.
> 
> 我重新搭建了环境

我已经在AutoDL平台的两台云服务器上搭建了环境, 都会卡住没法运行. 但是使用相同的指令在本地服务器上搭建环境是能够运行的. 所有服务器的系统都是 Ubuntu 20.04. 太奇怪了.

**Comment by wulinaaa** [comment]
> > > torchpack的版本是0.3.1
> > > 
> > > * p4 ![image](https://user-images.githubusercontent.com/45492880/263257341-786a7e9b-6ec3-4468-91ac-c4749db07c20.png)
> > >   请问你最后怎么解决的呢? 没有响应也不占GPU, 我不知道该如何下手去找bug.
> > 
> > 
> > 我重新搭建了环境
> 
> 我已经在AutoDL平台的两台云服务器上搭建了环境, 都会卡住没法运行. 但是使用相同的指令在本地服务器上搭建环境是能够运行的. 所有服务器的系统都是 Ubuntu 20.04. 太奇怪了.

你的pytorch安装的是gpu版本吗

**Comment by Sadwy** [comment]
是的, 是GPU版本, cuda版本也是和`nvcc -V`中的cuda版本一致的.
![image](https://github.com/zhijian-liu/torchpack/assets/45492880/0a585a9d-69ea-4034-9016-c8cf2e0344b7)

**Comment by wulinaaa** [comment]
> 是的, 是GPU版本, cuda版本也是和`nvcc -V`中的cuda版本一致的. ![image](https://user-images.githubusercontent.com/45492880/263259884-0a585a9d-69ea-4034-9016-c8cf2e0344b7.png)

![image](https://github.com/zhijian-liu/torchpack/assets/86940268/54353413-db9c-4920-876c-4c7a2b8090cf)
我的是这样的，你可以参考一下。我觉得大概率是环境没有装好

**Comment by Sadwy** [comment]
> > 是的, 是GPU版本, cuda版本也是和`nvcc -V`中的cuda版本一致的. ![image](https://user-images.githubusercontent.com/45492880/263259884-0a585a9d-69ea-4034-9016-c8cf2e0344b7.png)
> 
> ![image](https://user-images.githubusercontent.com/86940268/263260286-54353413-db9c-4920-876c-4c7a2b8090cf.png) 我的是这样的，你可以参考一下。我觉得大概率是环境没有装好

好的谢谢, 我再重新搭建环境试试.

**Comment by Sadwy** [comment]
问题已解决. 在我的问题中, torchpack无响应的原因是底层的mpirun运行时无响应. debug过程如下:
1. 使用apt-get安装torchpack底层库openmpi.
  - `apt-get install openmpi-bin openmpi-common libopenmpi-dev`
  - 运行时无响应无输出, mpirun无响应.
2. 使用apt-get安装mpich, 试图用其代替openmpi.
  - `apt-get install mpich`
  - 运行时报错, 原因是[torchpack不支持mpich](https://github.com/zhijian-liu/torchpack/issues/36).
3. 在[OpenMPI官网](https://www.open-mpi.org/software/ompi/v4.0/)下载压缩包解压安装openmpi.
  - 问题解决.
