### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/bin/sh'

### ISSUE THREAD

**Issue by Lilulululu** [zhijian-liu/torchpack#47]
Hello, when I run bevfusion for MIT I get torchpack\launch\launchers\drunner.py", line 104, in main
    os.execve('/bin/sh', ['/bin/sh', '-c', command], environ)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/sh'。
Windows does not have this file, how to change os.execve('/bin/sh', ['/bin/sh', '-c', command], environ) under windows。

**Comment by zhijian-liu** [comment]
You could try removing `/bin/sh` and `-c` in the file to see whether that works.
