### ISSUE TITLE
Are there any inbuilt visualising support for the losses?

### ISSUE THREAD

**Issue by sandeepnmenon** [zhijian-liu/torchpack#6]
I am using the e3d repo to train SPVCNN using torckpack.
Are there any inbuilt visualising support for the losses?
If not please point to an example of using any visualising frameworks (eg. tensorboard) along with torchpack.

Thank you.

**Comment by zhijian-liu** [comment]
`torchpack` will save the tensorboard log files to `runs/` by default. You can run `tensorboard --logdir runs/` to visualize the loss as well as accuracy.

**Comment by sandeepnmenon** [comment]
Yes I was able to do that. 
Thank you
