### ISSUE TITLE
How to debug code launched with torchpack?

### ISSUE THREAD

**Issue by cslxiao** [zhijian-liu/torchpack#7]
How to debug code launched with torchpack in IDE such as VSCode?
Thx.

**Comment by zhijian-liu** [comment]
I'm not sure about this as I usually debugged the code with prints.

**Comment by victor000000** [comment]
try CUDA_VISIBLE_DEVICES=1 MASTER_HOST=localhost:1235 python xxxxx.py {args}

**Comment by oliver0922** [comment]
Same question as above.
How to debug code launched with torchpack in IDE such as VSCode?

**Comment by SibylGao** [comment]
Maybe Pdb is what you need:
`import pdb; pdb.set_trace()`
