### ISSUE TITLE
No module named torchpack.launch.assets

### ISSUE THREAD

**Issue by amkurup** [zhijian-liu/torchpack#9]
I used pip3 to install torchpack. I have both python2 and python3 on my system and I prefer that usr/bin/python points to python2. How do I tell torchpack to look for python3?

**Comment by amkurup** [comment]
I think line 85 in launch > launchers > drunner.py needs to be changed to python3 ...
`command = 'python -m torchpack.launch.assets.silentrun ' + command`
Can you confirm this?

**Comment by amkurup** [comment]
I was able to change the above line and build from source. This fixed the issue! 
Thanks

**Comment by zhijian-liu** [comment]
Hi @amkurup, I just pushed a patch. Please take a look to see whether the issue has been solved. Thanks!

**Comment by amkurup** [comment]
This has definitely fixed my issue and is better than my quickfix! Thanks
